name: Build Github Pages
on:
  push:
    branches:
      - master
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
      - uses: actions/checkout@v2
      - id: Build-Vue
        uses: MathiusD/VuePagesAction@v1.0.0
        with:
          username: "MathiusD"
          reponame: "wakfu-theme-viewer"
          token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
          cname: wakfu-theme-viewer.waklab.fr
          frozenlockfile: false
